server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authentication-service
              uri: http://localhost:8020
              predicates:
                - Path=/api/v1/auth/**

app:
  auth:
    validate-jwt-path: http://localhost:8020/api/auth/validate
  jwt:
    secret: ${JWT_SECRET:VGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCB0b2tlbnMhISEhISEhISE=}