server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authentication-service
              uri: http://localhost:8020
              predicates:
                - Path=/api/v1/auth/**
            - id: post-service
              uri: http://localhost:8030
              predicates:
                - Path=/api/v1/posts/**
            - id: image-service
              uri: http://localhost:8010
              predicates:
                - Path=/api/v1/images/**
            - id: activity-service
              uri: http://localhost:8040
              predicates:
                - Path=/api/v1/activities/**

app:
  auth:
    validate-jwt-path: http://localhost:8020/api/auth/validate
  jwt:
    secret: ${JWT_SECRET:VGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCB0b2tlbnMhISEhISEhISE=}